name: Testing CI

on:
  push:
      branches: [ main ]
  pull_request:
      branches: [ main ]

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install gtest
      run: sudo apt install -y libgtest-dev
      - name: install cmake
      run: sudo apt install -y cmake
      - name: configure
      run: mkdir build && cd build && cmake -DBUILD_SAMPLE=OFF -DBUILD_TESTS=ON ..
      - name: compile
      run: cmake --build .
      - name: test
      run: ./test/test_all