name: Testing CI

on:
  push:
    branches: 
      - main
      - testing
  pull_request:
    branches:
      - main
      - testing

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install gtest
        run: sudo apt install -y libgtest-dev

      - name: Install CMake
        run: sudo apt install -y cmake

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake -DBUILD_SAMPLE=OFF -DBUILD_TESTS=ON ..

      - name: Compile
        run: |
          cd build
          cmake --build .

      - name: Test
        run: |
          cd build
          ./test/test_all
